server:
  port: 8828
spring:
  application:
    name: goods-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/one_web?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 111111q
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    prefix: classpath:/templates
    cache: false
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
    suffix: .html
  redis:
    host: localhost
    port: 6379

    pool:
      max-active: 8
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    #password: 111111q
  ##########################################kafka 服务配置
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: 1
      batch-size: 16384
      retries: 0
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  ##########################consumer about config##############################
    consumer:
      enable-auto-commit: true
      group-id: test-consumer-group
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


mybatis-plus:
  mapper-locations: classpath:/com/web/mapper/xml/*.xml
  #type-aliases-package: com.web.mapper


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/





