server:
  port: 8880
spring:
  application:
    name: redis-service
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      #password: 111111q
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/





